name: Upload Website

on:
  push:
    branches:
    - main

env:
  REACT_APP_HAPI_URL: ${{ secrets.HAPI_URL }}
  REACT_APP_ENVIRONMENT: "production"
  REACT_APP_COGNITO_CLIENT_ID: ${{ secrets.AWS_COGNITO_CLIENT_ID }}
  REACT_APP_COGNITO_URL: ${{ secrets.AWS_COGNITO_URL }}

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use node 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.15.1
      - run: npm ci
  build:
      needs: install
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [ 16.x]
      steps:
        - uses: actions/checkout@v3
        - name: Use node ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
        - run: npm install
        - run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        python-version: 3.9
    - name: Config AWS Cred
      run: |
        pip install awscliv2
        aws configure set region eu-west-1
        aws configure set output json
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} 
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: deploy with s3 sync and Invalidate CloudFront cache
      run: |
        npm install
        npm run build
        aws s3 sync ./build s3://${{ secrets.AWS_S3_BUCKET }}/
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
